### ISSUE TITLE
Missing variables

### ISSUE THREAD

**Issue by AlexandreGohier** [githubixx/ansible-kubernetes-playbooks#10]
Still in part 4 of your tutorial, trying to generate the Kubernetes configuration files using this playbook: 
ansible-kubernetes-playbooks/kubeauthconfig/kubelets.yml

It seems I am missing two variables for the playbook to work:
**k8s_config_cluster_name
k8s_config_directory**

![screen shot 2018-05-07 at 14 39 10](https://user-images.githubusercontent.com/37018962/39704151-c1c53016-520a-11e8-8c81-4ce8b9fa90e0.png)

![screen shot 2018-05-07 at 15 24 51](https://user-images.githubusercontent.com/37018962/39704167-d11d8e00-520a-11e8-9959-79c336ca1406.png)

- I'm guessing I can use whatever I want as a cluster name (unless the rest of your playbooks depend on a specific naming convention)? Can you please confirm?

- What about the k8s config directory? So far I have only set the **k8s_ca_conf_directory** variable, should they both be set to the same value?

I have an up-to-date cached inventory and I cannot find anything related to those two variables in there.

Thanks!

**Comment by githubixx** [comment]
I've defined `k8s_config_cluster_name`  and `k8s_config_directory` in `group_vars/all.yml`. Variables in this file are accessable by all roles and playbooks.

`I'm guessing I can use whatever I want as a cluster name (unless the rest of your playbooks depend on a specific naming convention)? Can you please confirm?`
Yes, you can basically use any name. I suggest to only use charters but TBH I haven't verifed if this a requirement. But better safe then sorry ;-)

`What about the k8s config directory? So far I have only set the k8s_ca_conf_directory variable, should they both be set to the same value?`
That's up to you but i suggest you use different directories. The content of the both directories don't have much in common regarding the files they contain. I've also placed the two variables in `group_vars/all.yml`:

```
k8s_config_directory: "/etc/k8s/configs" # Contains files like encryption-config.yaml and a few *.kubeconfig files
k8s_ca_conf_directory: "/etc/k8s/certs" # Contains everything certificate related like certificate authority files (CA), certificte signing requests (CSR), and stuff like that.
```
But you can use whatever directories you want of course. Just keep in mind that the directories must exist before you execute the playbook as it won't create it for you. At least not at the moment ;-)

**Comment by AlexandreGohier** [comment]
Ok thanks for the info, I didn't want to take reckless initiatives that would have compromised the use of your roles in the remaining steps...
