### ISSUE TITLE
Error generating kubeconfig: has no attribute 'ansible_tap0'

### ISSUE THREAD

**Issue by tscolari** [githubixx/ansible-kubernetes-playbooks#6]
Hey there,
I'm trying to follow this part of your blog post, but when I run the `kubeauthconfig/kubelets.yml` playbook it fails with this message:

```
TASK [Generate a kubeconfig file for each worker node (set-cluster)] **************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute u'ansible_tap0'\n\nThe error appears to have been in '/Users/tscolari/Workspace/infra/ansible-kubernetes-playbooks/kubeauthconfig/kubelets.yml': line 5, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  tasks:\n    - name: Generate a kubeconfig file for each worker node (set-cluster)\n      ^ here\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: 'dict object' has no attribute u'ansible_tap0'"}
```
Using `debug` I can't see anything with the `ansible_tap0` in the host. Did I miss anything?
I've been following the post step-by-step!

**Comment by githubixx** [comment]
Hi,
have you defined `peervpn_conf_interface` correctly in `group_vars/all.yml`? Because this task depends on this variable. By default the PeerVPN interface is `tap0`. If you run `ansible -m setup all | grep tap0` you should see the variable. Otherwise I suspect you maybe renamed the PeerVPN interface.

**Comment by tscolari** [comment]
The ouput of `ansible -m setup all | grep tap0` for me:

```
            "tap0",
        "ansible_tap0": {
            "device": "tap0",
            "tap0",
        "ansible_tap0": {
            "device": "tap0",
            "tap0",
        "ansible_tap0": {
            "device": "tap0",
```

I'm using the values from the post for the peerpvn_conf paramenters:

```
peervpn_conf_networkname: "peervpn"
peervpn_conf_psk: "..."
peervpn_conf_initpeers: "k8s-node-1.my-domain.com 7000"
peervpn_conf_enabletunneling: "yes"
peervpn_conf_interface: "tap0"
peervpn_conf_port: 7000
peervpn_conf_enableipv6: "no"
```

**Comment by tscolari** [comment]
It seems localhost doesn't have that, all the other hosts does

**Comment by githubixx** [comment]
In that case I would guess you have `localhost` in your `k8s_worker` Ansible host group. I can only guess but for PeerVPN role to create the `tap0` interface you need a file like `host_vars/k8s-node-1.my-domain.com` in your case (basically for every host you specify in `k8s_worker` group). Maybe you need a file `host_vars/localhost` with 

```
---
peervpn_conf_ifconfig4: "xxx.xxx.xxx.xxx/yy"
```
Could be that Ansible interprets one your your host as `localhost` despite that you've it assigned a "normal" fully qualified domain name like `k8s-node-1.my-domain.com`. So maybe go back where you created the PeerVPN interfaces and have a look if really all hosts needed have a `tap0` interface after you deploy the role.

**Comment by tscolari** [comment]
So I checked all hosts and they all have the `tap0` interface.

My hosts file is as follow:
```
[k8s_kubectl]
localhost ansible_connection=local

[k8s_ca]
localhost ansible_connection=local

[k8s_etcd]
k8s-node-[1:3].domain.com

[k8s:children]
k8s_controller
k8s_worker

[k8s_controller]
k8s-node-[1:3].domain.com

[k8s_worker]
k8s-node-[1:3].domain.com
```

(I'm using controllers == workers at the moment, not sure if that's the issue)

All my worker hosts have the `peervpn_config_ifconfig4` set (except for localhost):

```
peervpn_conf_ifconfig4: "10.3.0.101/24"
peervpn_conf_ifconfig4: "10.3.0.102/24"
peervpn_conf_ifconfig4: "10.3.0.103/24"
```

I'm quite new to ansible, but does this output
```
PLAY RECAP ******************************************************************************************************************************************************************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=1
```
means that step failed on the localhost?

**Comment by githubixx** [comment]
Haven't tried myself but "controllers == workers" shouldn't be a issue. 

Your Ansible output means that at least one task on one host failed. I currently have no idea why `kubeauthconfig/kubelets.yml` playbook fails with a error on localhost if the `[k8s_worker]` group is defined as in your last post. 

If you ran `ansible -m setup all` before executing the playbook Ansible's "fact cache" should be up2date and Ansible should be able to find that variables. But of course localhost has no PeerVPN `tap0` interface. But as `localhost` is not part of the `k8s_worker` group the task https://github.com/githubixx/ansible-kubernetes-playbooks/blob/master/kubeauthconfig/kubelets.yml#L6 shouldn't even consider `localhost`. The task itself runs on localhost that's for sure but only to execute the `kubectl` command to create the needed files.

Please execute the playbook with `ansible -vvv ...` to get more debug output. Maybe that helps.

**Comment by tscolari** [comment]
unfortunately `-vvv` didn't give any additional info. 

It's weird because when I do `-m setup all` I can see the `ansible_tap0` and other interfaces properties on all the workers. But when I debug print `hostsvars[]` the only host that has network interfaces showing is localhost. Should the output of `setup all` and `hostvars` be same?

Also, I'm running it without the cache options on in the `ansible.cfg`, so I'm guessing I getting the fresh stuff every time.
If I do turn the caching on, the error is different:

```
TASK [Generate a kubeconfig file for each worker node (set-cluster)] *******************************************
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'k8s_config_cluster_name' is undefined\n\nThe error appears to have been in '/Users/tscolari/Workspace/infra/ansible-kubernetes-playbooks/kubeauthconfig/kubelets.yml': line 36, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: Generate a kubeconfig file for each worker node (set-cluster)\n      ^ here\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: 'k8s_config_cluster_name' is undefined"}
```

**Comment by tscolari** [comment]
Ok, by adding that variable (`k8s_config_cluster_name`) and using cache it's working now :)

I thought the cache thing was an optional step, I think I got it wrong

**Comment by githubixx** [comment]
Ah, cool :smile: The problem is that some jobs needs host facts (e.g. like interface names) that're only available when Ansible gathered the facts before. But in this case e.g. the host is `localhost` (to execute `kubectl` locally) and that's why Ansible doesn't gather the host facts of the other hosts as they're not in the host group for this role/playbook.
That's the reason why we need the facts of the other hosts cached before some of the jobs work. I haven't had the time to figure out but I guess I could add a "gather fact" task at the beginning of every playbook so that caching isn't needed. But caching facts isn't that bad as it makes execution also a little bit faster. Not sure what route is the best.
But ATM make sure to run `ansible -m setup all` before the TTL of the facts cache is over (depending on what TTL you configured in ansible.cfg).
