### ISSUE TITLE
Wrong link to this repository in K8S tutorial part 4

### ISSUE THREAD

**Issue by AlexandreGohier** [githubixx/ansible-kubernetes-playbooks#9]
Hello again,

Moving forward with your great tutorial.

FYI, [in part 4](https://www.tauceti.blog/post/kubernetes-the-not-so-hard-way-with-ansible-at-scaleway-part-4/), you refer to this repository with the wrong link for the git clone command:

![screen shot 2018-05-07 at 14 35 05](https://user-images.githubusercontent.com/37018962/39702349-cba8a168-5204-11e8-92f2-79e0b661275c.png)

Wrong / dead link: 
`git clone https://github.com/githubixx/ansible-kubernetes-misc
`

New / working link: 
`git clone https://github.com/githubixx/ansible-kubernetes-playbooks
`

Thanks again!

**Comment by githubixx** [comment]
Thanks for reporting! Link fixed in the blog.
